apps:
  -
    name: server
    script: ./index.js
    watch: true
    ignore_watch: ['node_modules', 'runtime']
    log_date_format: YYYY-MM-DD HH:mm:ss.SSS
    error_file: ./runtime/logs/error.log
    out_file: ./runtime/logs/output.log

  -
    name: dev-server
    script: ./index.js
    watch: true
    ignore_watch: ['node_modules', 'runtime']
    max_restarts: 1
    log_date_format: YYYY-MM-DD HH:mm:ss.SSS
    error_file: ./runtime/logs/dev.error.log
    out_file: ./runtime/logs/dev.output.log
